import re

REGEX_WHITELIST = [
    r'/(^(dl|ns[12])\.)?dropbox\.com|^(dl)\.dropboxusercontent\.com$/',
    r'/(^(hub-api|global-api)\.airthin\.gs$|^ext-api\.airthings\.com$)/',
    r'/(^(pkg|electron)\.)?authy\.com$/',
    r'/(^(static|repo|download(s)?|dl|fw-(download|update))\.ubnt|^global\.(stun|turn)\.twilio|^(client|device|update)\.amplifi|^sp-dir\.uwn|ips1\.unifi-ai)\.com$/',
    r'/(^(x[0-9]\.c|(e[0-9]|r[0-9])\.o)\.lencr\.org$|^letsencrypt\.org$)/',
    r'/(^h(30494|20593)\.www[23]\.hp\.com$|^xmpp005\.hpeprint\.com$)/',
    r'/(i18n\.)?prismlauncher.org$/',
    r'/(profile\.accounts|detectportal|www)(\.)firefox\.com$|(aus5|www|(services\.)?addons|(versioncheck-bg|services)\.addons)(\.)mozilla\.org|(assets|(normandy|firefox-settings-attachments|content-signature-2)\.cdn)\.mozilla\.net|((firefox\.settings|classify-client)\.services|(token|push|shavar|location|sync-1-us-west1-g\.sync)\.services)(\.)mozilla\.com|^firefoxusercontent\.com$/',
    r'/^(((a)?live)\.)?github\.com$|^(repository-images|avatars)\.githubusercontent\.com$|^github\.githubassets\.com$/',
    r'/^(((cf-svcs|sus\.dhg|svcs|home|appcompatibility)\.)?myharmony\.com$|^(pubsub|ps-[0-9]{1,3})\.pubnub\.com)|accounts\.logi\.com$/',
    r'/^((0\.client-channel|android\.clients|mail|youtube-ui\.l|inbox|clients[1-9]|cse|ogs|play|pki-goog\.l|apis|plus\.l|www(3\.l)?|video-stats\.l|id)\.)?google.com|googleapis\.com|^(ssl\.)?gstatic\.com$|^(manifest|redirector)\.googlevideo\.com|(geo|yt)3\.ggpht\.com$/',
    r'/^(([0-9-]{1,3})+\.mydns|my)\.jdownloader.org$/',
    r'/^((aapi|se)\.)?shouldianswer\.net$/',
    r'/^((account|catalog)-public-service-prod0[0-9]|datarouter|turn\.rtcp\.on|entitlement-public-service-prod0[0-9]|friends-public-service-prod0[0-9]|launcher-public-service-prod0[0-9]|lightswitch-public-service-prod0[0-9]|merchantpool[0-9]|orderprocessor-public-service-ecomprod0[0-9]|payment-website-pci|xmpp-service-prod|auncher-public-service-prod\.ak|priceengine-public-service-ecomprod0[1-9]|library-service\.live\.use1a\.on|datarouter-prod\.ak)(\.ol)?\.epicgames\.com$/',
    r'/^((account|connect|api-(api-(ubiservices|uplayplusvault)|static-account|lb-prod-acc_ount-pdc|dmx\.upc)\.)ubisoft.com$|^((uplay)?connect|wallet\.ecom|public-ubiservices|useast1-public.aws-ubiservices|channel-service\.upc|public-ws-ubiservices|)\.ubi.com$/',
    r'/^((achievements|chat|d(evice\.auth|lassets-ssl)|lfghub-anonymous|eplists|updatepc|notificationinbox|p(eoplehub|r(ivacy|ofile))|rta|social|titlehub|userpresence|images-eds(-ssl)?|streaming|avty|xblmessaging|(xsts|title|user)\.auth|xccs)\.xboxlive\.com$|^(catalog|profile)\.gamepass\.com$|^www\.xboxab\.com$|^(beige)\.xboxservices\.com$)/',
    r'/^((advika|niya|alya|myra|rachita|mahi|amrita|vega|divya|priya|vanya|jaya|lisa|live|isha|anaya|ishita|garima|triya|kavya|navya|fw|pa-api)\.)?telldus\.com$/',
    r'/^((api|mqtt)-eu\.roborock\.com|(conf|ultronsplus)-eu-1316693915\.cos\.eu-frankfurt\.myqcloud\.com)$/',
    r'/^((apns|asustornasapi|update).)?asustor.com$/',
    r'/^((aur|mirrors|bbs|security|accounts|openpgpkey(\.master-key)?|pages|ping|repos|archive|status|wiki|lists|git|svn|www|mail|bugs|md|redirect|dev|monitoring|wiki|gitlab|download|security)\.)archlinux\.org$/',
    r'/^((broker|dauth|aauth)-lp1\.ndas\.srv|sun\.hac\.lp1\.d4c|broker\.lp1\.npns\.srv|receive-lp1\.dg\.srv|app-a04\.lp1\.npns\.srv|ctest\.cdn|aqua\.hac\.lp1\.d4c|tagaya\.hac\.lp1\.eshop|bcat-(list|data)-lp1\.cdn|capi\.lp1\.op2|nncs[12]-lp1\.n\.n\.srv|ctest-ul-lp1\.cdn|dragons\.hac\.lp1\.dragons|shop|consumer\.lp1\.npns\.srv|pushmo\.hac\.lp1\.eshop|bcat-topics-lp1\.cdn|accounts)\.nintendo\.net$|^((accounts).)?nintendo.com$/',
    r'/^((cdn(2)?|chat|storage|updates(2)?)\.)?signal\.org$/',
    r'/^((community|features|forums|dashboard|v4|assets|meta|metadata-static|plexamp|app|sonos|images|o1\.email|proxy|pubsub|staging|status|tvdb2|o2\.sg0|acoustid|clients|discover\.provider|downloads|scrobbles|lyricfind|mbz|metadata\.provider|songkick|together)?\.)?plex\.tv$|((resources-cdn|my|nine\.plugins|node|tvthemes)\.)?plexapp\.com|^([0-9-]{1,3})+\.\w+\.plex.direct$/',
    r'/^((discovery(-v[46])?|upgrades)\.)?syncthing\.net$/',
    r'/^((download)\.)?wireguard\.com$/',
    r'/^((gamedownloads|(auth-)?rgl-prod\.ros|rgl|prod\.cloud)\.)?rockstargames\.com$|^a\.rsg\.sc|^rockstar-api\.arkoselabs\.com$/',
    r'/^((registration|wanip4|rebindtest4|craftassets|mothership|backup)\.unraid\.net|([0-9]{1,3}-){3}[0-9]{1,3}\.([0-9a-z])+\.myunraid\.net)$/',
    r'/^((rog(-live-service)?|gaming-config|liveupdate01s|dlcdn((web)?imgs|rog)|www|mymessage|rog-content-platform|dlcdn-rogboxbu2|account)\.)?asus.com$/',
    r'/^((tpop-api)\.)?twitter\.com$|(pbs|ton|video|abs|(abs-(0|zero)))\.twimg.com$|^t\.co$/',
    r'/^((tracking|app|portal|account|www)\.)?postnord.com$/',
    r'/^((www|ipv6)\.msftconnecttest\.com$|^dns\.msftncsi\.com$)/',
    r'/^((www|z-p42-instagram\.c10r)\.)?instagram.com|^(s(content|tatic)\.)cdninstagram\.com$/',
    r'/^([0-9]\.(nz|android|openwrt|arch|ubnt|debian)\.)?pool\.ntp\.org$/',
    r'/^(auth|c(fg|hat|ontent-system|hat)|e(mbed|xternal-(accounts|users))|galaxy-(library|promos)|game(play|sdb)|images|login|marketing-sections|menu|notifications(-pusher(-aws)?)?|presence|r(ecommendations-api|emote-config)|www)\.gog\.com$/',
    r'/^(beehive|nucleo)\.neatocloud\.com$/',
    r'/^(cava(notification|internal)|mexx|www)\.bankid\.com$/',
    r'/^(current\.cvd|database|www)\.clamav\.net$/',
    r'/^(d([12]|ci)\.sophosupd\.com$|^4\.sophosxl\.net)$/',
    r'/^(data-cloud|www)\.flightradar24\.com$/',
    r'/^(eu\.(patch|version)|alert-eu|beta\.content-ui|us-legal)\.battle\.net|^(((eu\.)?api|eu\.cdn|level3(\.ssl)?)\.)?blizzard\.com$/',
    r'/^(ext2-(ams1|sto[21])|ext4-lhr1|ipv6check-http)\.steamserver\.net$|^steam-chat\.com$|^(client-update|community|clientconfig)\.akamai\.steamstatic\.com$|^(test|store)\.steampowered\.com$/',
    r'/^(geo|gdpr-wrapper|vendors)\.privacymanager\.io$|^maps\.infoplaza\.nl|^cluster\.api\.meteoplaza\.com$/',
    r'/^(images-ext-[1-9]|cdn|media|dl)\.?discordapp\.(com$|net$)|^((updates|status)\.)?discord\.com$|^(gateway|gateway-us-east1-[a-z])\.discord\.gg|^(latency)\.discord\.media$/',
    r'/^(livepatch(-files)?|contracts)\.canonical\.com$/',
    r'/^(n-(devs|wap|euw1-wap)-gw\.tplinkcloud\.com|^api-homecare-cloud\.i\.tplinknbu\.com)$/',
    r'/^(nrdp(60-appboot|-ipv6\.prod\.ftl|\.prod\.cloud)|android\.prod\.cloud|secure|push\.prod|nflx-android-tv\.prod\.partner)\.netflix\.(com|net)$/',
    r'/^(pro|broker|api)\.minibrew\.io$/',
    r'/^(px[0-9]|^a([0-9])?|^(m([0-9]|q\.gw)|openapi|apigw|images))\.tuyaeu\.com$/',
    r'/^(s(2)?\.)?youtube\.com$|^youtu\.be$|^youtube-nocookie\.com$|^(i(1)?|s)\.ytimg\.com$/',
    r'/^(time|path[1-3])\.xtracloud\.net/',
    r'/^(userlocation|messages|safebrowsing|play|steamcloud-eu-fra\.storage|fcm|android|maps|www|fonts|youtubei|firebaseremoteconfig|(notifications|gnpfesdk|geller|lamssettings|jnn|androidpay-users|deviceintegritytokens|playatoms|ulp1p|people|reach|semanticlocation|reminders|androidtvlauncherxfe|update)-pa|staging-locationhistory-pa\.sandbox|instantmessaging-pa-preprod-eu)\.googleapis.com$/',
    r'/^(wbsapi|static|sct01-ws|prod\.rudderstack)\.withings\.net$/',
    r'/^(websocket|stream|www|zebra|update|ocelot|stream-android|static)\.)?pushbullet.com$/',
    r'/^api([0-9])?[-\.].*((((((((teslacoilapps|accounts\.nintendo|minecraftservices|techlandonlineservices|gog|pushbullet|github|google|steampowered|blizzard|dropbox|twitter|soundcloud|authy|firefox|discogs|postnord|pushbullet|samsungcloud|telldus|unsplash)\.com|(audnex)\.us)|(snapcraft)\.io)|(signal|jdownloader)\.org)|(epicgames)\.dev$)|(ipdata)\.co)|(svt)\.se)|(plex)\.tv$)/',
    r'/^api\.waqi\.info$/',
    r'/^cdn\.fwupd\.org$/',
    r'/^connectivitycheck\.gstatic\.com$/',
    r'/^ext-api\.vasttrafik\.se$/',
    r'/^homebridge-gsh\.iot\.oz\.nu$/',
    r'/^https://automation0[12]\.verisure\.com$/',
    r'/^mypagesapi\.sectoralarm\.net$/',
    r'/^ocsp(2)?\.((digicert|globalsign|sectigo|sca1b\.amazontrust|starfieldtech|usertrust|(root(ca1|g2)\.amazontrust))\.com$|(pki)\.goog)|(swisssign|comodoca\.com\.cdn\.cloudflare)\.net$/',
    r'/^static\.xx\.fbcdn.net$/',
    r'/^track\.aliexpress\.com/',
    r'/^track\.earlybird\.se$/',
    r'/^tracking\.bring\.se$/',
    r'/^tracking\.earlybird\.delivery$/',
    r'/^www\.svt(static)?\.se$/',
]

REGEX = [
    re.compile(r'^ad(?:[sxv]?[0-9]*|system)[_.-](?:[^\s.]+\.){1,}|[_.-]ad(?:[sxv]?[0-9]*|system)[_.-]'),
    re.compile(r'([.\-_])?(logging|annons|crashlytics(reports)?|metrics|banner(s)?|marketing|analytics|telemetry|(stats|statistics)|events|track(ing)?|(insights\-)?collector|(d)?trace)([.\-_])?'),
    re.compile(r'(?:.*\.)?(imrworldwide\.com$|sentry\.io$|brandmetrics\.com|$brandmetrics\.com$|tsyndicate\.com$|adnxs\.com|moatads\.com$|app-measurement\.com$|admob\.com$|statsy\.net$|footprintdns\.com$|app-measurement\.com$|acuityads\.com$|doubleclick\.net$|ezcybersearch\.com$|affiliator\.(?:com|nu)$|affiliaxe\.com$|datadoghq\.(?:com$|eu$)|findbetterresults\.com|funnelytics\.io|tradedoubler\.com)'),
    re.compile(r'^(?:.+?([\.\-_]))?adse?rv(er?|ice)?s?[0-9]*([\.\-_])'),
    re.compile(r'^(cbox4\.ignorelist|atlas-upd)\.com$|^(claudfront|allowlisted)\.net|^hsdps\.cc$|^ads-tm-glb\.click$'),
    re.compile(r'^allegro'),
    re.compile(r'^beacons?[0-9]*([\.\-_])'),
    re.compile(r'^mads\.'),
    re.compile(r'^count(?:er(s)?)?([\.\-_])'),
    re.compile(r'^footprints([\.\-_])'),
    re.compile(r'^pixel(?:s)?([\.\-_])'),
    re.compile(r'^app\.adjust\.(?:world|com|net\.in$)'),
    re.compile(r'^(developer)\.asustor\.com$'),
    re.compile(r'^galaxy-client-reports\.gog\.com$'),
    re.compile(r'^svt\.d[0-9]\.sc\.omtrdc\.net$'),
    re.compile(r'^deb\.fdmpkg\.org$'),
    re.compile(r'^(track-my-delivery\.net|unsubscribeprime\.info)$'),
    re.compile(r'^(.*)?(duc3k|amazingtodaynotsaidhimherwhathe|ankabuttech|tadogem|deveparty|plus-lema|es-megado|focustopbreed78d|fermonesgobide|sertvs|jqscr|jqueryns|maximumpushtodaynotnowbut|motiontodaynotgogoodnowok|mavelecgr|eerier-safety\.000webhostapp|catknock|specialblueitems|violetlovelines|panel\.cheater-zone|allfamax|client\.cheater-zone|bitcoinpricealertexpert|coindexalerter|uniswapdataprice|immagirls\.myvnc|alpatrik|justinstalledpanel|damnater)\.com$'),
    re.compile(r'[-\w]+\.casalemedia\.com\s*'),
    re.compile(r'[-\w]+\.actonservice\.com\s*'),
    re.compile(r'[-\w]+\.smartadserver\.com\s*'),
    re.compile(r'[-\w]+\.advertnative\.com\s*'),
    re.compile(r'/(^|\.)xn--p1ai$/'),
]

LIST_WHITELIST = ["rain-alarm.com","activision.com","chomikuj.pl","firebasedynamiclinks.googleapis.com","epic.download","geotrust.com","cloudflare.com","evyy.net","adjust.com","alimentacionchino.com","cbsivideo.com","pluto.tv","onetrust.com","cbsi.com","tiqcdn.com","instagram.com","typekit.net","robertsspaceindustries.com","soundcloud.com","ipqualityscore.com","suyu.dev","plex.direct","revanced.net","atomixhq.baby","atresmedia.com","leinad4mind.top","split.io","github.io","gitlab.com","raw.githubusercontent.com","digidip.net","chollometro.digidip.net","tradedoubler.com","plex.tv","fapality.com","virtualbox.org","ddos-guard.net","bbva.es","cn.pccomponentes.com","es.spankbang.com","tinder.com","haiku-os.org","milanuncios.com","aliexpress.com","alicdn.com","go-mpulse.net","nsw2u.com","waaw.to","raidrive.com","netflixmirror.com","oraclecloud.com","eset.com","mparticle.com","cookielaw.org","mmcdn.com","azure.com","nickchan.lol"]

DOMAIN_LIST = ["file.co.pl","apps.co.pl","metadsp.co.uk","i-mobile.co.jp","myishop.co.uk","free-counter.co.uk","adskeeper.co.uk","smlog.co.kr","searchteria.co.jp","free-counters.co.uk","procook.co.uk","rakuten.co.jp","jwespeex.co.in","momentummedia.com.au","admaster.com.cn","rozetka.com.ua","scorptec.com.au","sina.com.cn"]

SUBDOMAIN_PATTERNS = {
    "vinted-": "*.*",
    "hotel-": "*.*",
    "piwik.": "*",
    "matomo.": "*",
    "metric.": "*",
    "olx-": "*.*",
    "olx.": "*",
    "xn--": "*.*",
    "news-": "*.*",
    "news.": "*",
    "newcp.": "*",
    "newcpp.": "*",
    "oascentral.": "*",
    "tr.": "*",
    "trk.": "*",
    "a8.": "*",
    "a8clk.": "*",
    "a8cv.": "*",
    "mobileoffers-": "*.*",
    "mon-": "*.*",
    "mdp-appconf-": "*.*"
}

DOMAIN_WHITELIST = ["rain-alarm.com","activision.com","chomikuj.pl","firebasedynamiclinks.googleapis.com","epic.download","geotrust.com","cloudflare.com","evyy.net","adjust.com","alimentacionchino.com","cbsivideo.com","pluto.tv","onetrust.com","cbsi.com","tiqcdn.com","instagram.com","typekit.net","robertsspaceindustries.com","soundcloud.com","ipqualityscore.com","suyu.dev","plex.direct","revanced.net","atomixhq.baby","atresmedia.com","microsoft.com","leinad4mind.top","split.io","github.io","gitlab.com","raw.githubusercontent.com","digidip.net","chollometro.digidip.net","tradedoubler.com","plex.tv","fapality.com","virtualbox.org","ddos-guard.net","bbva.es","pccomponentes.com","es.spankbang.com","tinder.com","haiku-os.org","milanuncios.com","aliexpress.com","alicdn.com","go-mpulse.net","nsw2u.com","waaw.to","raidrive.com","netflixmirror.com","oraclecloud.com","eset.com","elamigos-games.net","mparticle.com","cookielaw.org","mmcdn.com","azure.com","nickchan.lol"]

DOMAIN_WHITELIST2 = ["3gppnetwork.org","microsoft.com","lencr.org","symantec.com","signal.org","t-mobile.com","tuyomovil.com","symcd.com","verisign.com","viero.com","symcb.com","zonamovil.com.pa","sectigo.com","geotrust.com","letsencrypt.org","mycricket.com","movistar.cl","movistar.com.ar","movistar.com.co","movistar.com.ec","movistar.com.uy","movistar.com.ve","movistar.com","movistar.cr","movistar.es","movistar.gt","movistar.mx","movistar.ni","movistar.pa","movistar.pe","movistar.sv","movistar.ve","3ireland.ie","accv.es","github.io","entrust.net","ocsp-responder.com","live.com","office.com","office.net","office365.com","wosign.com","globalsign.com","mopera.net","usertrust.com","trustwave.com","trust-provider.com","digicert.com","amazontrust.com","vodafone.al","vodafone.co.uk","vodafone.com.eg","vodafone.com.mt","vodafone.com.qa","vodafone.es","vodafone.gr","vodafone.hu","vodafone.ie","vodafone.is","vodafone.it","vodafone.net.nz","vodafone.pt","comodo.com","comodo.net","googleapis.com","orange.acte","orange.at","orange.cm","orange.co.uk","orange.com.do","orange.es","orange.fr","orange.lu","orange.mms","orange.ne","orange.nl","orange.pl","orange.re","orange.smartphone","orange.tn","orange.ug","orange.video","orange.web","orange.world","euskaltel.mobi","thawte.com","pepephone.com"]

DOMAIN_WHITELIST3 = "mmsc."
